[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:xvfb]
command=/usr/bin/Xvfb :0 -screen 0 %(ENV_SCREEN_RESOLUTION)s
priority=10
autorestart=true

[program:fluxbox]
command=/usr/bin/fluxbox
environment=DISPLAY=":0"
priority=20
autorestart=true

[program:x11vnc]
command=/usr/bin/x11vnc -display :0 -forever -shared -nopw -rfbport 5900
priority=30
autorestart=true

[program:novnc]
command=/usr/bin/websockify --web /usr/share/novnc 6080 localhost:5900
priority=40
autorestart=true
